name: personal_portfolio
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  animate_do: ^3.3.4
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  file_saver: ^0.2.14
  firebase_core: ^3.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_gen: ^5.8.0
  flutter_screenutil: ^5.9.3
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  icons_launcher: ^3.0.0
  percent_indicator: ^4.2.4
  rename: ^3.0.2
  url_launcher: ^6.3.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  build_runner: ^2.4.14
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/cvs/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900

flutter_assets:
  assets_path: assets/images/
  output_path: lib/Core/helpers
  filename: image_assets.dart
  field_prefix: null
